<?php
/**
 * This file has been @generated by a phing task from CLDR version 28.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Do not modify this file directly!
 */

return array (
  'AZ' => 'Азәрбајҹан',
  'BR' => 'Бразилија',
  'CN' => 'Чин',
  'DE' => 'Алманија',
  'FR' => 'Франса',
  'IN' => 'Һиндистан',
  'IT' => 'Италија',
  'JP' => 'Јапонија',
  'RU' => 'Русија',
  'US' => 'Америка Бирләшмиш Штатлары',
);
