<?php
/**
 * This file has been @generated by a phing task from CLDR version 35.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'BR' => 'Brazil',
  'CN' => 'Tsina',
  'DE' => 'Alemanya',
  'FR' => 'Pransiya',
  'GB' => 'Hiniusang Gingharian',
  'IN' => 'India',
  'IT' => 'Italya',
  'JP' => 'Hapon',
  'PH' => 'Pilipinas',
  'RU' => 'Russia',
  'US' => 'Estados Unidos',
);
