<?php
/**
 * This file has been @generated by a phing task from CLDR version 44.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'AC' => 'Isla Ascensión',
  'AX' => 'Islas Åland',
  'BA' => 'Bosnia-Herzegovina',
  'CG' => 'República del Congo',
  'CI' => 'Costa de Marfil',
  'GS' => 'Islas Georgia del Sur y Sándwich del Sur',
  'IC' => 'Islas Canarias',
  'RO' => 'Rumania',
  'SA' => 'Arabia Saudita',
  'TL' => 'Timor Oriental',
  'UM' => 'Islas Ultramarinas de EE.UU.',
);
