<?php
/**
 * This file has been @generated by a phing task from CLDR version 43.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'BR' => 'ᠪᠷᠠᠽᠢᠯ',
  'CN' => 'ᠬᠢᠳᠠᠳ',
  'DE' => 'ᠭᠧᠷᠮᠠᠨ',
  'FR' => 'ᠫᠷᠠᠨ᠋᠋ᠼᠠ',
  'GB' => 'ᠶᠡᠺᠡ ᠪᠷᠢᠲ᠋ᠠᠨᠢ',
  'IN' => 'ᠡᠨᠡᠳᠬᠡᠭ᠌',
  'IT' => 'ᠢᠲ᠋ᠠᠯᠢ',
  'JP' => 'ᠶᠠᠫᠣᠨ',
  'MN' => 'ᠮᠣᠩᠭᠣᠯ',
  'RU' => 'ᠣᠷᠣᠰ',
  'US' => 'ᠠᠮᠸᠷᠢᠻᠠ ᠎ᠢᠢᠨ ᠨᠢᠭᠡᠳᠥᠭᠰᠡᠠ ᠡᠣᠯᠣᠰ',
);
