<?php
/**
 * This file has been @generated by a phing task from CLDR version 39.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'BR' => 'ब्राजील',
  'CN' => 'चाइना',
  'DE' => 'जर्मनी',
  'FR' => 'फ़्रांस',
  'GB' => 'यूनाइटेड किंगडम',
  'IN' => 'भारत',
  'IT' => 'इटली',
  'JP' => 'जापान',
  'RU' => 'रशिया',
  'US' => 'अमेरिका',
);
