<?php
/**
 * This file has been @generated by a phing task from CLDR version 40.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'AC' => 'острво Асенсион',
  'BY' => 'Бјелорусија',
  'CC' => 'Кокосова (Килинг) острва',
  'CG' => 'Конго',
  'CV' => 'Кабо Верде',
  'CZ' => 'Чешка Република',
  'DE' => 'Њемачка',
  'GS' => 'Јужна Џорџија и Јужна Сендвичка острва',
  'GU' => 'Гвам',
  'HK' => 'Хонгконг (САО Кине)',
  'KN' => 'Свети Китс и Невис',
  'KP' => 'Сјеверна Кореја',
  'MK' => 'Сјеверна Македонија',
  'MO' => 'САР Макао',
  'MP' => 'Сјеверна Маријанска острва',
  'NF' => 'острво Норфок',
  'NU' => 'Нијуе',
  'PM' => 'Свети Пјер и Микелон',
  'PS' => 'палестинске територије',
  'RE' => 'Реунион',
  'UM' => 'Спољна острва САД',
  'VC' => 'Свети Винсент и Гренадини',
  'VG' => 'Британска Дјевичанска Острва',
  'VI' => 'Америчка Дјевичанска Острва',
);
