<?php
/**
 * This file has been @generated by a phing task from CLDR version 39.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * @internal Please do not require this file directly.
 * It may change location/format between versions
 *
 * Do not modify this file directly!
 */

return array (
  'AC' => 'ostrvo Asension',
  'BY' => 'Bjelorusija',
  'CC' => 'Kokosova (Kiling) ostrva',
  'CG' => 'Kongo',
  'CV' => 'Kabo Verde',
  'CZ' => 'Češka Republika',
  'DE' => 'Njemačka',
  'GS' => 'Južna Džordžija i Južna Sendvička ostrva',
  'GU' => 'Gvam',
  'HK' => 'Hongkong (SAO Kine)',
  'KN' => 'Sveti Kits i Nevis',
  'KP' => 'Sjeverna Koreja',
  'MK' => 'Sjeverna Makedonija',
  'MO' => 'SAR Makao',
  'MP' => 'Sjeverna Marijanska ostrva',
  'NF' => 'ostrvo Norfok',
  'NU' => 'Nijue',
  'PM' => 'Sveti Pjer i Mikelon',
  'PS' => 'palestinske teritorije',
  'RE' => 'Reunion',
  'UM' => 'Spoljna ostrva SAD',
  'VC' => 'Sveti Vinsent i Grenadini',
  'VG' => 'Britanska Djevičanska Ostrva',
  'VI' => 'Američka Djevičanska Ostrva',
);
