<?php
/**
 * This file has been @generated by a phing task from CLDR version 28.0.0.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Do not modify this file directly!
 */

return array (
  'AF' => 'Afuganistani',
  'BJ' => 'Benini',
  'CG' => 'Kongo',
  'CI' => 'Kodivaa',
  'CY' => 'Kuprosi',
  'IR' => 'Uajemi',
  'LI' => 'Lishenteni',
  'MG' => 'Bukini',
  'MM' => 'Myama',
  'NF' => 'Kisiwa cha Norfok',
  'NG' => 'Nijeria',
  'TL' => 'Timori ya Mashariki',
);
